# Generated by Django 4.2.5 on 2023-11-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
