# Generated by Django 4.2.5 on 2023-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(),
        ),
    ]
