# Generated by Django 4.2.5 on 2023-11-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0003_user_access_token_user_graduation_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorizationCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
