# Generated by Django 4.2.5 on 2024-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0004_user_graduating_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('club_attendance_admin', 'Club Attendance admin'), ('bathroom_pass_admin', 'Bathroom Pass admin')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
