# Generated by Django 4.2.5 on 2024-05-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0005_permmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_code',
            new_name='uuid',
        ),
    ]
