# Generated by Django 4.2.5 on 2023-11-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oauth2_provider', '0007_application_post_logout_redirect_uris'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authserver', '0005_remove_user_graduation_year_remove_user_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
