# Generated by Django 4.2.5 on 2024-06-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authserver', '0006_rename_email_code_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
